apiVersion: v1
kind: Service              
metadata:
  name: app-test-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 80               
    protocol: TCP          
    targetPort: 80         
  selector:                
    app: app-test       


#создать сервис
kubectl create -f app-test-lb.yml

#проверить состояние сервиса
kubectl get svc
